name = "github_contributions_widget"
main = "build/worker/shim.mjs"
compatibility_date = "2024-12-04"

[build]
command = "cargo install -q worker-build && worker-build --release"

[dev]
port = 8787

[vars]
GITHUB_TOKEN = ""

